### ISSUE TITLE
librime file not found

### ISSUE THREAD

**Issue by rqy2002** [wsw0108/scoop-bucket#1]
The url `https://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-librime-1.5.3-2-any.pkg.tar.xz` is 404 now. Maybe you need update it?

**Comment by wsw0108** [comment]
@rqy2002 can you try #2 ？

**Comment by jiahut** [comment]
after update librime: 1.8.5-1 (latest version)

rime--load-dynamic-module: Module could not be opened: "c:/Users/zhijia/AppData/Roaming/.emacs.d/elpa/rime-20230212.1425/librime-emacs.dll", "找不到指定的模块。"

**Comment by rqy2002** [comment]
@wsw0108 it works, but I also get
```
load-file: Module could not be opened: ".../.local/straight/build-30.0.50/rime/librime-emacs.dll", "找不到指定的模块。"
```
But maybe it's a bug with emacs-rime?

**Comment by wsw0108** [comment]
应该是需要重新编译得到librime-emacs.dll，毕竟librime版本升级了。
不过也可能是librime-emacs不支持这个版本的librime

**Comment by rqy2002** [comment]
我确实重新编译了librime-emacs.dll。我试一下重新安装 emacs-rime

**Comment by rqy2002** [comment]
这并不work。emacs的\*Message\* buffer：
```
gcc lib.c -o librime-emacs.dll -fPIC -O2 -Wall -I c:/Users/rqy/scoop/apps/librime/1.8.5-1/include/ -I c:/Users/rqy/AppData/Local/Emacs/include/ -shared -L c:/Users/rqy/scoop/apps/librime/1.8.5-1/lib/ -Wl,-rpath c:/Users/rqy/scoop/apps/librime/1.8.5-1/lib/ -lrime
Compile succeed!
Loading c:/Users/rqy/.emacs.d/.local/straight/build-30.0.50/rime/librime-emacs.dll (module)...
load-file: Module could not be opened: "c:/Users/rqy/.emacs.d/.local/straight/build-30.0.50/rime/librime-emacs.dll", "找不到指定的模块。"
```

**Comment by rqy2002** [comment]
我确认其使用的 `gcc` 亦是 scoop 安装版本。

**Comment by wsw0108** [comment]
用depends之类软件看看librime-emacs.dll的dll依赖

**Comment by rqy2002** [comment]
librime.dll缺少了libleveldb.dll和libyaml-cpp.dll的依赖x

**Comment by rqy2002** [comment]
安装这两个包之后就没问题了，不过我不知道怎么改然后交PR :frowning_face:

**Comment by jiahut** [comment]
> libleveldb

https://repo.msys2.org/mingw/x86_64/ 这里没有找到哇😭

**Comment by wsw0108** [comment]
https://github.com/wsw0108/scoop-bucket/commit/fc9f42a2627ec550d02bfb57dd997171984c8b36
